### ISSUE TITLE
Do not work anymore : update for the new site ?

### ISSUE THREAD

**Issue by yogeek** [vikbez/radiooooo-cli#3]
Hi ! 

Is there still an API to interect with the new website https://radiooooo.app/ please ?
this script does not seem to work anymore

Thanks

**Comment by cbertram** [comment]
You can use [Jouzo's fork](https://github.com/Jouzo/radiooooo-cli) or [my fork](https://github.com/cbertram/radiooooo-cli) thereof.
I'd love to have a merge back into this repo. This is a bit messy until @vikbez adds a license (issue #2), though.

**Comment by vikbez** [comment]
What license would be good ?

**Comment by vikbez** [comment]
Just added MIT license
feel free to create an MR ! Thanks :)
